### ISSUE TITLE
Make it work on Gnome 3.24

### ISSUE THREAD

**Issue by DidierLoiseau** [kgaut/gnome-shell-audio-output-switcher#11]
[extensions.gnome.org](https://extensions.gnome.org/extension/1028/gnome-shell-audio-output-switcher/) report it as outdated, and the extension is disabled in Gnome 3.24.0.
I'm using it on Ubuntu 17.04.

**Comment by kgaut** [comment]
I've just released a version that works under gnome-shell 3.24.

Grab it from here, or via https://extensions.gnome.org/extension/1028/gnome-shell-audio-output-switcher/
