### ISSUE TITLE
gnome 3.22

### ISSUE THREAD

**Issue by NNois** [kgaut/gnome-shell-audio-output-switcher#7]
Hi,
This wonderfull extension doesn't work on 3.22 (i'm in manjaro)
What can i do exactly to make it work ?

**Comment by kgaut** [comment]
You can try with a modification like : #1 #4 

I don't own a gnome shell 3.22 for now, so let us know if it worked. And submit a PR if you can.

Regards.

Kevin

**Comment by NNois** [comment]
Hi,
That worked perfectly !
Adding 3.22 to the list then the extensions shows up in tweak tool. Sorry I don't know how to commit in github.

Cheers

**Comment by kgaut** [comment]
Ok,

I'll release an "official" version for gnome 3.22 later.

thanks for your feedback.

Kevin
